In [5]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

df=pd.read_csv(r"C:\Users\vamsv\Downloads\metafinals.csv")
df['interests']=[[i] for i in df['interests']]
df['course']=[[i] for i in df['course']]
df

,Unnamed: 0,id,first_name,last_name,email,gender,university,grad_year,course,interests,project_id
0,0,1,Cherianne,Jeal,cjeal0@vkontakte.ru,Female,Pennsylvania State University - Berks-Lehigh V...,1996,[PhD- Computer Science],[devOps],874
1,1,2,Norina,Kief,nkief1@odnoklassniki.ru,Agender,Hawassa University,2008,[PhD- Mechatronics],"[SQL, cybersecurity, python, js]",828
2,2,3,Kalinda,Byham,kbyham2@reddit.com,Female,Bucknell University,2009,[B.Tech- Electrical Engineering],"[digital marketing, AWS, SQL, mobile app devel...",650
3,3,4,Barron,Grundell,bgrundell3@cdbaby.com,Male,International University of Novi Pazar,1984,[PhD- Electrical Engineering],"[flask, webdev, penetration testing]",927
4,4,5,Ambrosius,Rolling,arolling4@example.com,Male,Barclay College,2011,[B.Tech- Electrical Engineering],"[cloud infrastructure, cloud computing, Android]",999
...,...,...,...,...,...,...,...,...,...,...,...
995,995,996,Brinna,Farlow,bfarlowrn@usnews.com,Female,"Washington State University, Tri-Cities",2003,[M.Tech- Electrical Engineering],"[robotics, cloud computing]",585
996,996,997,Kirbie,Duxbarry,kduxbarryro@digg.com,Female,Balikesir University,2006,[PhD- Computer Science],[cybersecurity],573
997,997,998,Donalt,Briggs,dbriggsrp@trellian.com,Male,Royal Academy of Music,2010,[PhD- Electrical Engineering],"[AWS, Android, ethical hacking, penetration te...",892
998,998,999,Abey,O'Gormley,aogormleyrq@ed.gov,Male,Our Lady of Fatima University,1993,[PhD- Mechatronics],[devOps],577
999,999,1000,Chrotoem,Thal,cthalrr@networksolutions.com,Male,Grand Valley State University,2004,[M.Tech- Computer Science],[smart contracts],937

In [6]:
tfidf = TfidfVectorizer(tokenizer=lambda x: x, lowercase=False)

projects_tfidf = tfidf.fit_transform(df['interests'])
course_tfidf = tfidf.fit_transform(df['course'])

project_similarity = linear_kernel(projects_tfidf, projects_tfidf)
course_similarity = linear_kernel(course_tfidf, course_tfidf)
combined_similarity=project_similarity+course_similarity/2

c:\Users\vamsv\face\lib\site-packages\sklearn\feature_extraction\text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [7]:
def get_recommendations(student_name, num_recommendations=3):
    student_index = df[df['first_name'] == student_name].index[0]
    similar_students_indices = combined_similarity[student_index].argsort()[::-1][1:]
    recommended_students = df.iloc[similar_students_indices[:num_recommendations]]
    return recommended_students[['first_name', 'last_name', 'interests']]


student_name = 'Donalt'

recommendations = get_recommendations(student_name)
print(f"Recommended students for {student_name}:")
print(recommendations)

Recommended students for Donalt:
    first_name last_name                                          interests
499       Rosa    Jurgen                                 [data warehousing]
128   Marigold     Lober  [UI/UX design, artificial intelligence, penetr...
416       Nils  Schurcke                  [business intelligence, robotics]